services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env

  webserver:
    container_name: web
    build:
      context: .
      dockerfile: .docker/webserver/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:80"

  db:
    container_name: app_db
    image: 'bitnami/postgresql:15.0.0'
    volumes:
      - 'db_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: db_user
      POSTGRESQL_PASSWORD: db_pass
      POSTGRESQL_DATABASE: app

volumes:
  db_data: